# LMS Queries for CyberJab

query moduleQuery($relativePath: String!) {
  module(relativePath: $relativePath) {
    ...ModuleParts
  }
}

query trackQuery($relativePath: String!) {
  track(relativePath: $relativePath) {
    ...TrackParts
  }
}

query lessonQuery($relativePath: String!) {
  lesson(relativePath: $relativePath) {
    ...LessonParts
  }
}

query labQuery($relativePath: String!) {
  lab(relativePath: $relativePath) {
    ...LabParts
  }
}
